---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 16574.
--- DateTime: 2024/11/4 20:50
---
--比较线程标识与锁中标识是否一致  且保持了原子性
if(redis.call('get',KEYS[1])==ARGV[1]) then
    --释放锁 del KEYS
    return redis.call('del',KEYS[1])
end
return 0